### ISSUE TITLE
Show tree count in the composer message

### ISSUE THREAD

**Issue by jamesmills** [TreewareEarth/plant#1]
This will get the total trees in the Treeware forest for all packages using Treeware

```
https://api.ecologi.com/users/treeware/trees'
```

This is what we use to get a count for a specific package

```
$response = (new Client())->request('get', 'https://api.ecologi.com/users/treeware/trees', [
                'query' => [
                    'ref' => md5(Str::lower($package->owner . '/' . $package->package_name)),
                ],
            ]);
```

**Comment by ostark** [comment]
https://github.com/TreewareEarth/plant/blob/main/tests/__snapshots__/OutputTest__package_list_of_command__1.txt
Added in  https://github.com/TreewareEarth/plant/commit/7f1ed40643613f7ec9f88a87bc0bb5fdff963788

**Comment by jamesmills** [comment]
I've just run a test install of a package using this package but I didn't get the above message. Am I missing something?

**Comment by ostark** [comment]
The test mocks the actual API call and the real integration wasn't tested.

**Comment by ostark** [comment]
The "tree count" output is visible for the `composer treeware` command only.

**Intention:** 
It involves API calls. Running them during the actual `composer require / update` is risky to me. It's shouldn't break, but it could.

**Comment by jamesmills** [comment]
Makes sense, thanks.
